# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-11 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeTest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('illustration', models.CharField(max_length=100)),
            ],
        ),
    ]
